#!/usr/bin/env bash


export PREV_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export PREV_LIBRARY_PATH="$LIBRARY_PATH"
export PREV_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
export PREV_CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH"
export PREV_PYTHONPATH="$PYTHONPATH"

